# Generated by Django 3.1 on 2021-04-19 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(blank=True, max_length=11, verbose_name='Telefon')),
                ('cinsiyyet', models.CharField(blank=True, choices=[('K', 'Kişi'), ('Q', 'Qadın'), ('O', 'Başqa')], max_length=1, verbose_name='Cinsiyyət')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Hakkında')),
                ('photo', models.ImageField(default='default_profile.png', upload_to=users.models.upload_to, verbose_name='Şəkil')),
                ('brithday', models.DateField(blank=True, null=True, verbose_name='Doğrum tarixi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi adı')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profillər',
            },
        ),
    ]
